print("Welcome to the tip calculator!")
total = float(input("What was the total bill? $" ))
tip = int(input("How much tip would you like to give? 10, 12, or 15? "))
number_of_people = int(input("How many people to split the bill? "))
all = (total) * (1 + int(tip) / 100)
print(f"Each person should pay: ${round(all / int(number_of_people), 2)}")